#!/bin/sh
#

start ()
{
        echo " "
#    echo " Checking SSH server..."
#	if grep -q 'PermitRootLogin' /etc/ssh/sshd_config
#	then
#       	echo " Patching SSH server"
#		sed -i -e /.*PermitRootLogin.*/d -e "\$aPermitRootLogin yes" /etc/ssh/sshd_config
#		/etc/init.d/sshd restart
#	fi
}
stop ()
{
        echo " "
}
restart()
{
        stop
        start
}
        case "$1" in
                start)
                        start; ;;
                stop)
                        stop; ;;
                restart)
                        restart; ;;
                *)
                        echo "Usage: $0 {start|stop|restart}"
                        exit 1
        esac
exit $?
