<hr>
@subsection design_overview_doc_sec_yms yang-manager-server repository - YANG application
<hr>
@par
The modules in the yang-manager-server repository provide the code for supporting YANG (ORAN).

@par
<b>Detailed Design</b>
@par
More details of the yang-manager-server design can be found here:
<A HREF="./yang-manager-server-doc/index.html" target="_blank"><b>YANG manager server Design Document</b></A>
<BR>

