#!/bin/sh

#dirs=hwmon0 hwmon1 hwmon10 hwmon11 hwmon12 hwmon13 hwmon2 hwmon3 hwmon4 hwmon5 hwmon6 hwmon7 hwmon8 hwmon9
#
#for d in $dirs ; do
#	echo $d
#done

for d in hwmon0 hwmon1 hwmon10 hwmon11 hwmon12 hwmon13 hwmon2 hwmon3 hwmon4 hwmon5 hwmon6 hwmon7 hwmon8 hwmon9 ; do
	echo $d
	mkdir -p $d
	cp /sys/class/hwmon/$d/*_input $d/
	cp /sys/class/hwmon/$d/name $d/
done
