/*!
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * \file      DpdAppTestInterface.h
 * \brief     Test interface for DPD@APP
 *
 *
 * \details   Auto-generated by gentool. Contains test interface definitions.
 *
 */

#ifndef __DPDAPPTESTINTERFACE__H_
#define __DPDAPPTESTINTERFACE__H_


//=============================================================================================================
// INCLUDE
//=============================================================================================================
#include "TestInterface.h"

//=============================================================================================================
// CLASS
//=============================================================================================================

namespace Mplane {

class DpdAppTestInterface: public TestInterface
{
public:
    DpdAppTestInterface();
    ~DpdAppTestInterface();
};

} // Mplane

#endif /* __DPDAPPTESTINTERFACE__H_*/
