/*!
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * \file      Zcu111TestInterface.h
 * \brief     Test interface for ZCU111
 *
 *
 * \details   Auto-generated by gentool. Contains test interface definitions.
 *
 */

#ifndef __ZCU111TESTINTERFACE__H_
#define __ZCU111TESTINTERFACE__H_


//=============================================================================================================
// INCLUDE
//=============================================================================================================
#include "TestInterface.h"

//=============================================================================================================
// CLASS
//=============================================================================================================

namespace Mplane {

class Zcu111TestInterface: public TestInterface
{
public:
    Zcu111TestInterface();
    ~Zcu111TestInterface();
};

} // Mplane

#endif /* __ZCU111TESTINTERFACE__H_*/
