/*!
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * \file      DiscoveryLabTestInterface.cpp
 * \brief     Test interface for DISCOVERY@LAB
 *
 *
 * \details   Auto-generated by gentool. Contains test interface definitions.
 *
 */


//=============================================================================================================
// INCLUDE
//=============================================================================================================
#include "DiscoveryLabTestInterface.h"

#include "DiscoveryLabDiscoveryTestHandler.h"


using namespace Mplane ;

//=============================================================================================================
// PUBLIC
//=============================================================================================================

//-------------------------------------------------------------------------------------------------------------
DiscoveryLabTestInterface::DiscoveryLabTestInterface()
{
	DiscoveryLabDiscoveryTestHandler::registerMethods(/* IRtiMsgParser */ *this, /* IRtiSettings */ *this) ;


}

//-------------------------------------------------------------------------------------------------------------
DiscoveryLabTestInterface::~DiscoveryLabTestInterface()
{
}
