<hr>
@subsection design_overview_doc_oranlibs  oran-libs repository - ORAN Libraries
<hr>
@par
The oran-libs repository contains third-party libraries used to create ORAN applications.


@par
<b>Detailed Design</b>
@par
More details of the functionality provided as part of the <b>oran-libs</b> repository can be found here:
<A HREF="./oran-libs-doc/index.html" target="_blank"><b><i>oran-libs</i> - ORAN Libraries Design Document</b></A>
<BR>


