/*!
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * \file      Zcu111MplaneOranrrhSettings.h
 * \brief     Limits variable settings for ZCU111-MPLANE-ORANRRH
 *
 *
 * \details   Auto-generated by gentool. Contains limits variable definitions. Please add your own
 * code between the %%--> and <--%% comment lines (any code outside these comments will be discarded
 * next time the generate tool is run)
 *
 *
 */


#ifndef __ZCU111MPLANEORANRRHSETTINGS__H_
#define __ZCU111MPLANEORANRRHSETTINGS__H_

#include "ILimitsSettings.h"

// Add any specific includes here %%-->

// <--%%

//=============================================================================================================
// CLASS
//=============================================================================================================

namespace Mplane {

class Zcu111MplaneOranrrhSettings : public ILimitsSettings
{
public:
	Zcu111MplaneOranrrhSettings() ;
	virtual ~Zcu111MplaneOranrrhSettings() ;

	/**
	 * Perform registration of any settings
	 */
	virtual void registerSettings() override ;

// Add any extra methods %%-->

// <--%%

} ;

}

#endif /* __ZCU111MPLANEORANRRHSETTINGS__H_ */
