#!/bin/sh
# SDP


start ()
{
    echo " Checking 1G ethernet interface name..."
    
    # ifconfig -a | grep encap:Ethernet
    # 1         2    3               4      5
	# ens       Link encap:Ethernet  HWaddr 00:0A:35:00:22:01  
	# eth1      Link encap:Ethernet  HWaddr 00:0A:35:00:00:02  
    
    eth0mac=
    eth1G=
    for device in $(ifconfig -a | grep encap:Ethernet | awk '{print $1;}'); do
    	echo $device
    	
    	# does this device support 1G ?
    	if $(ethtool $device 2>&1 |grep -q 1000baseT); then
    		# At present, the 10G interface doesn't work with ethtool, so if this grep finds the string
    		# then we've found our 1G interface
    		eth1G=$device
    	fi

		# If eth0 already exists then get it's MAC
		if [ $device == "eth0" ]; then
			eth0mac=$(ifconfig -a | grep encap:Ethernet | grep eth0 | awk '{print $5;}')
			echo "ETH0 MAC=$eth0mac"
		fi
    done
    
    if [ -n "$eth1G" ]; then
    	echo "Found 1G device: $eth1G"
    	
    	# If it's already set to "eth0" then we can stop
    	if [ "$eth1G" == "eth0" ]; then
    		echo "1G interface already set to eth0"
    		return
    	else
    		eth1Gmac=$(ifconfig -a | grep encap:Ethernet | grep $eth1G | awk '{print $5;}')
			echo "1G ETH MAC=$eth1Gmac"
    	
    		# See if there's already an "eth0" interface
    		if [ -n "$eth0mac" ]; then
    		
    			# swap
    			ifconfig eth0 down
    			ifconfig $eth1G down 
    			ifrename xxx $eth0mac eth0 $eth1Gmac $eth1G $eth0mac
    		else
    			# just rename
    			ifconfig $eth1G down 
    			ifrename eth0 $eth1Gmac
    		fi
    	fi
    fi
}
stop ()
{
	echo " "
}
restart()
{
    stop
    start
}

case "$1" in
    start)
            start; ;;
    stop)
            stop; ;;
    restart)
            restart; ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit $?
