<hr>
@subsection design_overview_doc_sec3_0b  ros repository - Reusable Operating System
<hr>
@par
The Linux OS build for a products controller board is stored in this repository and built as a stand-alone
entity that can be loaded onto a board order for it to boot up with a minimum set of functionality.

@par
<b>Details</b>
@par
More details of the functionality provided as part of the <b>ros</b> repository can be found here:
<A HREF="./ros-doc/index.html" target="_blank"><b>OS Document</b></A>
<BR>

@par
<b>3rd Party Documentation</b>
@par
Documentation for TinyXML2 can be found here:
<A HREF="./tinyxml2/index.html" target="_blank"><b>TinyXML2</b></A>
<BR>

