#!/bin/sh
#
# Run application-specific init scripts
#

action="${1:-start}"

##----------------------------------------------------------------------------------------------------------------------
# handle error
##----------------------------------------------------------------------------------------------------------------------
errorMsg()
{
    echo >&2 "******* $@ *******"
}

##----------------------------------------------------------------------------------------------------------------------
# log a message
##----------------------------------------------------------------------------------------------------------------------
logMsg()
{
	msg="[$(date +%T)]APP-INIT: $*"
	echo "$msg"
}

##----------------------------------------------------------------------------------------------------------------------
# appstart()
# run app init files
##----------------------------------------------------------------------------------------------------------------------
appstart()
{
	## Application scripts get merged in with any OS init scripts - everything ends up in /etc/init.d where
	## most people would expect them to be!
	logMsg "Starting system init scripts..."
	for i in /etc/init.d/app.d/*.sh ; do
      if [ -f $i -a -x $i ] ; then
         logMsg "---------"
         logMsg "Starting $i"
         $i start
         logMsg "Started $i"
      fi
	done

}

##----------------------------------------------------------------------------------------------------------------------
# appstop()
##----------------------------------------------------------------------------------------------------------------------
appstop()
{
    logMsg "Stopping system init scripts ..."
    for i in $(ls -1 /etc/init.d/app.d/*.sh | sort -r) ; do
	if [ -f $i -a -x $i ] ; then
	    logMsg "Stopping $i"
	    $i stop
	fi
    done
}


##=== MAIN =============================================================================================================

case $action in
    start)
		appstart
	;;
    stop)
		appstop
	;;
    restart)
		appstop
		appstart
	;;
    *)
	echo >&2 "$0 - Unknown action $action"
esac


