#!/bin/sh
#
# Ensure we have a unique set of ssh server keys for this board, but only create them once
#

KEYSTORE_DIR=/nandflash/etc/ssh
[ -d $KEYSTORE_DIR ] || mkdir -p $KEYSTORE_DIR

case "$1" in
  start)
    # Restore keys from backup
    cp -p $KEYSTORE_DIR/*_key* /etc/ssh 2>/dev/null
    
    # Need to ensure permissions are correct
    chmod 0644 /etc/ssh/*_key.pub
    chmod 0600 /etc/ssh/*_key
  
  	# Check to see if we have any keys - if there are some then we can stop
  	keys=$(ls /etc/ssh/*_key*  2>/dev/null )
  	if [ -n "$keys" ]; then
  		exit 0
  	fi
  	
  	# Need to create them
  	/usr/bin/ssh-keygen -A
  	
  	# now back them up
  	cp -p /etc/ssh/*_key* $KEYSTORE_DIR/
	sync
	;;
	
  stop)
	;;
	
  restart|reload)
	"$0" start
	;;
	
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

